// landing for gRPC code generated by tonic-build

pub(crate) mod types {
    tonic::include_proto!("tbco.chain.types");
}

pub(crate) mod node {
    tonic::include_proto!("tbco.chain.node");
}

pub(crate) mod watch {
    tonic::include_proto!("tbco.chain.watch");
}
